"Bazel dependencies"

module(
    name = "com_booking_rules_patchelf_prebuilt",
    version = "0.0.0",
)

bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "platforms", version = "1.1.0")

bazel_dep(name = "gazelle", version = "0.51.0", dev_dependency = True)
bazel_dep(name = "aspect_gazelle_prebuilt", version = "0.0.18", dev_dependency = True)
bazel_dep(name = "bazel_lib", version = "3.3.1", dev_dependency = True)
bazel_dep(name = "buildifier_prebuilt", version = "8.5.1.2", dev_dependency = True)

patchelf_prebuilt = use_extension("//patchelf_prebuilt:extensions.bzl", "patchelf_prebuilt")
patchelf_prebuilt.toolchain()
use_repo(patchelf_prebuilt, "patchelf_prebuilt_toolchains")

register_toolchains("@patchelf_prebuilt_toolchains//:all")

patchelf_sources = use_extension(
    "//tools:patchelf_sources.bzl",
    "patchelf_sources",
    dev_dependency = True,
)
patchelf_sources.register()
use_repo(patchelf_sources, "patchelf_sources_v0.14.5")

bazel_dep(name = "rules_cc", version = "0.2.18", dev_dependency = True)
bazel_dep(name = "llvm", version = "0.8.4", dev_dependency = True)

register_toolchains(
    "@llvm//toolchain:all",
    dev_dependency = True,
)
